export const data = {
  kind: "youtube#videoListResponse",
  etag: "ofNZf0-SHn_-kH3B-UkQf0SISXQ",
  items: [
    {
      kind: "youtube#video",
      etag: "rEmnj2D3MaxwwzptYVo4MnIC5nk",
      id: "SRyk6t77Er8",
      snippet: {
        publishedAt: "2023-02-25T03:00:08Z",
        channelId: "UCDNvRZRgvkBTUkQzFoT_8rA",
        title: "[ENG] 커피 한잔은 핑계고",
        description:
          "6년 전, 동네 주민인 태현이랑 커피 한잔 하자~ 했는데 그걸 지금에야 하네요?\n마침 연석이도 시간이 맞아 집 근처에서 모였는데요.\n\n사실 다~~ 핑계고🐓\n떠들어제끼는 걸로 멍뭉이판 한번 만들어 보려고 만났습니다🔥\n\nㅡㅡㅡ\n유선배 복지 콘텐츠 🐓핑계고🐓\n우리도 언제 올릴지 몰라요 ⚠불시 업로드⚠\n☁구독 & 좋아요 & 알림설정 필수☁\n\n👇’뜬뜬’ 소식 보러가기\nhttps://instagram.com/ddeun._.ddeun\n\n#뜬뜬 #핑계고 #유재석 #차태현 #유연석 #커피\n.\n.\n*본 콘텐츠와 무관한 내용의 댓글과 출연자에 대한 무분별한 욕설, 비난 및 조롱 등 악의적인 댓글은 무통보 삭제될 수 있습니다.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/SRyk6t77Er8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/SRyk6t77Er8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/SRyk6t77Er8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/SRyk6t77Er8/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/SRyk6t77Er8/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "뜬뜬 DdeunDdeun",
        categoryId: "23",
        liveBroadcastContent: "none",
        localized: {
          title: "[ENG] 커피 한잔은 핑계고",
          description:
            "6년 전, 동네 주민인 태현이랑 커피 한잔 하자~ 했는데 그걸 지금에야 하네요?\n마침 연석이도 시간이 맞아 집 근처에서 모였는데요.\n\n사실 다~~ 핑계고🐓\n떠들어제끼는 걸로 멍뭉이판 한번 만들어 보려고 만났습니다🔥\n\nㅡㅡㅡ\n유선배 복지 콘텐츠 🐓핑계고🐓\n우리도 언제 올릴지 몰라요 ⚠불시 업로드⚠\n☁구독 & 좋아요 & 알림설정 필수☁\n\n👇’뜬뜬’ 소식 보러가기\nhttps://instagram.com/ddeun._.ddeun\n\n#뜬뜬 #핑계고 #유재석 #차태현 #유연석 #커피\n.\n.\n*본 콘텐츠와 무관한 내용의 댓글과 출연자에 대한 무분별한 욕설, 비난 및 조롱 등 악의적인 댓글은 무통보 삭제될 수 있습니다.",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "gvPb250a8bnpyaVHVO4BItcIJ0o",
      id: "tCanx5qEUVg",
      snippet: {
        publishedAt: "2023-02-25T13:37:57Z",
        channelId: "UCF3UEVPt5zZTlBVJwDG317g",
        title:
          "[아는형님] ＂ 라면은 20봉지 정도? ＂ 6봉 강호동도 한 수 접는 쯔양의 월드 클래스 먹성🌟｜핫클립｜JTBC 230225 방송 외",
        description:
          "햄버거 21개 라면 20봉지 \n곱창 16m 고기 4kg \n\n다 뿌시는(?) 쯔양의 월드 클래스 먹성↗\n\n#아는형님 #핫클립 #쯔양\n\n[JTBC봐야지] 구독하기☞ http://asq.kr/VgFZ3\n\n------------------------------------------------------\n* 영상 속 프로그램은?\n\n【아는 형님｜Knowing Brothers】\nhttps://tv.jtbc.co.kr/jtbcbros\n------------------------------------------------------",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/tCanx5qEUVg/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/tCanx5qEUVg/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/tCanx5qEUVg/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/tCanx5qEUVg/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/tCanx5qEUVg/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "JTBC Voyage",
        tags: [
          "genre:토크쇼",
          "format:하이라이트",
          "source:연예",
          "type:방송",
          "series:아는형님",
          "topic:썰",
          "person:쯔양",
          "person:강호동",
          "쯔양",
          "먹방",
          "mukbang",
          "쯔양 먹방",
          "쯔양 라면",
          "쯔양 햄버거",
          "쯔양 곱창",
          "강호동 먹방",
          "강호동 라면",
          "강호동 6봉",
          "대식가",
          "크리에이터",
          "유튜버",
          "월클",
          "심으뜸",
          "김계란",
          "슈카",
          "피지컬100",
          "햄최몇",
          "쯔양 먹성",
          "쯔양 위",
          "쯔양 몸무게",
          "이수근",
          "강호동",
          "김희철",
          "서장훈",
          "민경훈",
          "김영철",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title:
            "[아는형님] ＂ 라면은 20봉지 정도? ＂ 6봉 강호동도 한 수 접는 쯔양의 월드 클래스 먹성🌟｜핫클립｜JTBC 230225 방송 외",
          description:
            "햄버거 21개 라면 20봉지 \n곱창 16m 고기 4kg \n\n다 뿌시는(?) 쯔양의 월드 클래스 먹성↗\n\n#아는형님 #핫클립 #쯔양\n\n[JTBC봐야지] 구독하기☞ http://asq.kr/VgFZ3\n\n------------------------------------------------------\n* 영상 속 프로그램은?\n\n【아는 형님｜Knowing Brothers】\nhttps://tv.jtbc.co.kr/jtbcbros\n------------------------------------------------------",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "6mnYnsK28nLAdAyDH7bcy4btez8",
      id: "RPJP9_P1YXA",
      snippet: {
        publishedAt: "2023-02-26T07:23:33Z",
        channelId: "UC9gxOp_-R78phMHmv2bW_sg",
        title: "다시 시작된 LA에서 혼자살기⎥🇺🇸이민15",
        description:
          "미국 이민 브이로그15\n다시 미국에 돌아왔어요. 득근 화이팅\n\n\n🪵🍛 ☕️ 🛌💛\n • Email  :  wonjileelife@gmail.com\n • Instagram  :  https://www.instagram.com/im1g/\n • Book(저서)  : http://bit.ly/323YAbO\n • 톱밥꼰주(부채널) : https://bit.ly/3zvfsg5",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/RPJP9_P1YXA/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/RPJP9_P1YXA/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/RPJP9_P1YXA/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/RPJP9_P1YXA/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/RPJP9_P1YXA/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "원지의하루",
        tags: [
          "미국 이민",
          "미국 자취",
          "LA 브이로그",
          "미국 브이로그",
          "여행 브이로그",
          "세계여행 브이로그",
        ],
        categoryId: "22",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title: "다시 시작된 LA에서 혼자살기⎥🇺🇸이민15",
          description:
            "미국 이민 브이로그15\n다시 미국에 돌아왔어요. 득근 화이팅\n\n\n🪵🍛 ☕️ 🛌💛\n • Email  :  wonjileelife@gmail.com\n • Instagram  :  https://www.instagram.com/im1g/\n • Book(저서)  : http://bit.ly/323YAbO\n • 톱밥꼰주(부채널) : https://bit.ly/3zvfsg5",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "iFap72pEww6iiYywmmgK47fflyQ",
      id: "Za6EgFb96f4",
      snippet: {
        publishedAt: "2023-02-26T14:45:55Z",
        channelId: "UCkbJc8jMcTXwhtmN5VMwfXg",
        title:
          "[16회 하이라이트] 괜찮겠어? 난 한계를 모르는데^_^ '독립 대행사 대표'로 새롭게 도전하는 이보영 | 대행사 | JTBC 230226 방송",
        description:
          "[16회 하이라이트] \n괜찮겠어? 난 한계를 모르는데^_^\n'독립 대행사 대표'로 새롭게 도전하는 고아인(이보영)\n\n📌 공홈에서 리플레이 : https://tv.jtbc.co.kr/agency\n📌 #티빙에서스트리밍 : https://tving.onelink.me/xHqC/1vihef6r",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/Za6EgFb96f4/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/Za6EgFb96f4/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/Za6EgFb96f4/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/Za6EgFb96f4/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/Za6EgFb96f4/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "JTBC Drama",
        tags: [
          "대행사",
          "이보영",
          "조성하",
          "손나은",
          "한준우",
          "전혜진",
          "대행사하이라이트",
          "대행사16회하이라이트",
          "대행사16회",
          "대행사최종회",
          "대행사최종회하이라이트",
          "대행사요약",
          "대행사몰아보기",
          "대행사다시보기",
          "이보영드라마",
          "이보영대행사",
          "손나은드라마",
          "손나은대행사",
          "JTBC대행사",
          "JTBC드라마",
          "토일드라마",
          "JTBC토일드라마",
          "대행사공식영상",
          "조성하대행사",
          "조성하드라마",
          "한준우드라마",
          "전혜진드라마",
          "회사",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title:
            "[16회 하이라이트] 괜찮겠어? 난 한계를 모르는데^_^ '독립 대행사 대표'로 새롭게 도전하는 이보영 | 대행사 | JTBC 230226 방송",
          description:
            "[16회 하이라이트] \n괜찮겠어? 난 한계를 모르는데^_^\n'독립 대행사 대표'로 새롭게 도전하는 고아인(이보영)\n\n📌 공홈에서 리플레이 : https://tv.jtbc.co.kr/agency\n📌 #티빙에서스트리밍 : https://tving.onelink.me/xHqC/1vihef6r",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "tBCPSKcSMAcWXqe7r-zymwZ-hKU",
      id: "vriz12vC3oQ",
      snippet: {
        publishedAt: "2023-02-24T23:00:41Z",
        channelId: "UCYeeEwH_s9yD9HQe4e2JuBw",
        title:
          "[#미스터트롯2] 감성 천재들의 감성 정면 승부! 나상도의 '내가 바보야' VS 황민호의 '님은 먼 곳에' - 본선4차 1R 라이벌매치 #TV조선조이 (230223 방송)",
        description:
          "* 미성년자 오디션 영상의 경우, 미성년자 보호를 위해 댓글창을 활성화하지 않겠습니다. 양해 부탁드립니다.\n\n미스터트롯2 응원 투표 안내!! \nhttps://entertain.daum.net/poll/24207\n\n(1) 스마트폰에서 '카카오톡' 실행 \n(2) 하단 메뉴에서 \"뷰(눈동자)\" 버튼 클릭 \n(3) 상단의 '카카오TV' 메뉴 클릭 후 '#미스터트롯2' 버튼 클릭 \n(4) 온라인 투표배너 클릭 후 나만의 트롯스타 7명 선택 \n(5) 투표하기 누르면 완료!!!\n\n#미스터트롯2 #황민호 #나상도 \n\n🎪 구독과 좋아요 🎪\nTV CHOSUN JOY 구독하기 ☞ https://bit.ly/3hpEUr1\u200b\nTV CHOSUN : https://www.youtube.com/user/TVchosun",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/vriz12vC3oQ/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/vriz12vC3oQ/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/vriz12vC3oQ/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/vriz12vC3oQ/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/vriz12vC3oQ/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "TVCHOSUN JOY",
        tags: [
          "미스터트롯2",
          "미스트롯",
          "미스트롯2",
          "미스터트롯",
          "뽕숭아학당",
          "뽕학당",
          "사랑의콜센타",
          "사콜",
          "화요청백전",
          "금요일은밤이좋아",
          "금밤",
          "금요일에만나요",
          "화요일은밤이좋아",
          "화밤",
          "화요일에만나요",
          "불후의 명곡",
          "불타는 트롯맨",
          "국민가수",
          "국가수",
          "국가부",
          "국가가 부른다",
          "가요제",
          "송가인",
          "임영웅",
          "영탁",
          "이찬원",
          "김호중",
          "정동원",
          "장민호",
          "김희재",
          "양지은",
          "홍지윤",
          "김다현",
          "김태연",
          "김의영",
          "별사랑",
          "은가은",
          "장윤정",
          "김연자",
          "진성",
          "이홍기",
          "츄",
          "이달의 소녀",
          "이달소",
          "강다니엘",
          "알고보니 혼수상태",
          "알혼",
          "이현우",
          "이은지",
          "김해준",
          "신지",
          "현영",
          "코요태",
          "붐",
          "김성주",
          "박지현",
          "최수호",
          "강태풍",
          "장송호",
          "윤준협",
          "강재수",
          "임채평",
          "고정우",
          "정민찬",
          "이하준",
          "마커스강",
          "김용필",
          "성민",
          "성리",
          "선율",
          "박건우",
          "황민호",
          "진욱",
          "영광",
          "황민우",
          "오찬성",
          "임찬",
          "송도현",
          "서지유",
          "정예준",
          "박성온",
          "고강민",
          "이찬성",
          "정형찬",
          "최우진",
          "송민준",
          "박서진",
          "진해성",
          "안성훈",
          "길병민",
          "추혁진",
          "나상도",
          "시절인연",
          "별빛 같은 나의 사랑아",
          "가시오",
          "뜨거운 안녕",
          "물레방아 도는데",
          "수은등",
          "내가 바보야",
          "님은 먼 곳에",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title:
            "[#미스터트롯2] 감성 천재들의 감성 정면 승부! 나상도의 '내가 바보야' VS 황민호의 '님은 먼 곳에' - 본선4차 1R 라이벌매치 #TV조선조이 (230223 방송)",
          description:
            "* 미성년자 오디션 영상의 경우, 미성년자 보호를 위해 댓글창을 활성화하지 않겠습니다. 양해 부탁드립니다.\n\n미스터트롯2 응원 투표 안내!! \nhttps://entertain.daum.net/poll/24207\n\n(1) 스마트폰에서 '카카오톡' 실행 \n(2) 하단 메뉴에서 \"뷰(눈동자)\" 버튼 클릭 \n(3) 상단의 '카카오TV' 메뉴 클릭 후 '#미스터트롯2' 버튼 클릭 \n(4) 온라인 투표배너 클릭 후 나만의 트롯스타 7명 선택 \n(5) 투표하기 누르면 완료!!!\n\n#미스터트롯2 #황민호 #나상도 \n\n🎪 구독과 좋아요 🎪\nTV CHOSUN JOY 구독하기 ☞ https://bit.ly/3hpEUr1\u200b\nTV CHOSUN : https://www.youtube.com/user/TVchosun",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "CZmjTyJFJNeRVHXAsc5S3wzKP2Y",
      id: "uOgpAfiAQmo",
      snippet: {
        publishedAt: "2023-02-26T09:00:07Z",
        channelId: "UCGX5sP4ehBkihHwt5bs5wvg",
        title: "[한글자막] CL에게 롤리팝을 묻다",
        description:
          "#CL #컨디션 #컨디션스틱 #피식대학 #피식쇼\n\n\nFollow the host of PSICK SHOW on instagram right now!\n- YONGJU LEE : https://www.instagram.com/denver_yongju/\n- JAEHYUNG JUNG : https://www.instagram.com/hell773h/\n- MINSU KIM : https://www.instagram.com/mukgostudent/\n- PSICK UNIV official : https://www.instagram.com/psickuniv/",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/uOgpAfiAQmo/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/uOgpAfiAQmo/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/uOgpAfiAQmo/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/uOgpAfiAQmo/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/uOgpAfiAQmo/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "피식대학Psick Univ",
        categoryId: "23",
        liveBroadcastContent: "none",
        localized: {
          title: "[한글자막] CL에게 롤리팝을 묻다",
          description:
            "#CL #컨디션 #컨디션스틱 #피식대학 #피식쇼\n\n\nFollow the host of PSICK SHOW on instagram right now!\n- YONGJU LEE : https://www.instagram.com/denver_yongju/\n- JAEHYUNG JUNG : https://www.instagram.com/hell773h/\n- MINSU KIM : https://www.instagram.com/mukgostudent/\n- PSICK UNIV official : https://www.instagram.com/psickuniv/",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "2jAvk2DNkUBrS-jnt0ojHdxztRA",
      id: "jOuNq3aQcB8",
      snippet: {
        publishedAt: "2023-02-25T13:30:20Z",
        channelId: "UC78PMQprrZTbU0IlMDsYZPw",
        title:
          "열린 서진이네 닫힘..🙂 손님이 있었는데? 아니요 없어요.😐 #highlight #서진이네 EP.1",
        description:
          "티빙에서 스트리밍 : https://tving.onelink.me/xHqC/30a78d6f\n\n일곱 빛깔 호수를 품은 멕시코에서\n#서진이네 OPEN!\n\n식당 경영에 진심인 사장 #이서진\n이사로 승진한 #정유미\n주방의 실세로 거듭난 #박서준\n서진이네 분위기 메이커 #최우식 \n설거지요정 새 인턴 #김태형\n\n오늘도 어서오세요 :)\n서진이네 EP.1\ntvN 매주 금요일 오후 8시 50분!\n\n#티빙에서스트리밍",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/jOuNq3aQcB8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/jOuNq3aQcB8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/jOuNq3aQcB8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/jOuNq3aQcB8/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/jOuNq3aQcB8/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "tvN",
        tags: [
          "김말이",
          "김밥",
          "김태형",
          "나영석",
          "대박기원",
          "떡볶이",
          "라면",
          "만두",
          "먹방",
          "박서준",
          "분식",
          "뷔",
          "사장",
          "서진이네",
          "승진",
          "식당",
          "실세",
          "요리",
          "음식",
          "이사",
          "이서진",
          "인턴",
          "장사",
          "정유미",
          "정직원",
          "직금",
          "최우식",
          "튀김",
          "티빙에서스트리밍",
          "판매",
          "핫도그",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title:
            "열린 서진이네 닫힘..🙂 손님이 있었는데? 아니요 없어요.😐 #highlight #서진이네 EP.1",
          description:
            "티빙에서 스트리밍 : https://tving.onelink.me/xHqC/30a78d6f\n\n일곱 빛깔 호수를 품은 멕시코에서\n#서진이네 OPEN!\n\n식당 경영에 진심인 사장 #이서진\n이사로 승진한 #정유미\n주방의 실세로 거듭난 #박서준\n서진이네 분위기 메이커 #최우식 \n설거지요정 새 인턴 #김태형\n\n오늘도 어서오세요 :)\n서진이네 EP.1\ntvN 매주 금요일 오후 8시 50분!\n\n#티빙에서스트리밍",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "34ZBn0qzd0GxNnCRfNYmOevc2Ww",
      id: "QyxMXPLDVMc",
      snippet: {
        publishedAt: "2023-02-25T06:00:07Z",
        channelId: "UCszFjh7CEfwDb7UUGb4RzCQ",
        title: "[짐승친구들] 얼죽아",
        description:
          "이 만화는 무료로 웃겨줍니다!\n(평일은 저녁 6시, 주말은 오후 3시 업로드~!)\n\n[배급 : 빅픽처팀] [기획 : 비크리스피] [각본 : 짤태식]\n\n☆★짐승친구들을 만날 수 있는 방법★☆\nhttps://bigpictureteam.marpple.shop/kr\n\n☆★짤툰 멤버십 가입★☆\nhttps://www.youtube.com/channel/UCszFjh7CEfwDb7UUGb4RzCQ/join\n\nEnglish channel \nhttps://www.youtube.com/channel/UCULM7gWHnK03eB1UfWS4JUw\n\nJapan channel\nhttps://www.youtube.com/channel/UC8UBjcRjZFkl8SkzDWmD83g\n\nChinese channel\nhttps://space.bilibili.com/507866514/\nhttps://www.youtube.com/channel/UCHj_iUpiS1I6fPYFu2KLZXQ\n\nVietnam channel\nhttps://www.youtube.com/channel/UCwIqQ2ke-F6GVCSKeLtOY6A\n\n#짤툰#애니메이션#짐승친구들#얼죽아",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/QyxMXPLDVMc/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/QyxMXPLDVMc/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/QyxMXPLDVMc/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/QyxMXPLDVMc/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/QyxMXPLDVMc/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "짤툰",
        categoryId: "1",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title: "[짐승친구들] 얼죽아",
          description:
            "이 만화는 무료로 웃겨줍니다!\n(평일은 저녁 6시, 주말은 오후 3시 업로드~!)\n\n[배급 : 빅픽처팀] [기획 : 비크리스피] [각본 : 짤태식]\n\n☆★짐승친구들을 만날 수 있는 방법★☆\nhttps://bigpictureteam.marpple.shop/kr\n\n☆★짤툰 멤버십 가입★☆\nhttps://www.youtube.com/channel/UCszFjh7CEfwDb7UUGb4RzCQ/join\n\nEnglish channel \nhttps://www.youtube.com/channel/UCULM7gWHnK03eB1UfWS4JUw\n\nJapan channel\nhttps://www.youtube.com/channel/UC8UBjcRjZFkl8SkzDWmD83g\n\nChinese channel\nhttps://space.bilibili.com/507866514/\nhttps://www.youtube.com/channel/UCHj_iUpiS1I6fPYFu2KLZXQ\n\nVietnam channel\nhttps://www.youtube.com/channel/UCwIqQ2ke-F6GVCSKeLtOY6A\n\n#짤툰#애니메이션#짐승친구들#얼죽아",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "deM8NJrpDNoDnRS0Mq9I_ZNGO54",
      id: "gNCqySyeyus",
      snippet: {
        publishedAt: "2023-02-23T13:30:15Z",
        channelId: "UCkinYTS9IHqOEwR1Sze2JTw",
        title:
          '하늘에서 쏟아진 수백 마리…"재앙의 전조?" 쏟아진 목격 / SBS / 오클릭',
        description:
          "〈오! 클릭〉 마지막 검색어는 '하늘에서 쏟아진 물고기'입니다.\n\n도로에 은빛 비늘의 물고기들이 널브러져 있습니다.\n\n호주 북부의 작은 마을 '라자마누'에서 벌어진 일인데요, 물고기 수백 마리가 비와 함께 하늘에서 쏟아져 내린 것입니다.\n\n현장을 목격한 주민은 갑자기 하늘에서 물고기가 땅과 지붕으로 우수수 떨어졌고, 이 가운데 상당수는 죽지 않은 채 바닥에서 펄떡거렸다고 하는데요.\n\n이 물고기는 호주에서 흔히 볼 수 있는 농어과 민물고기로 약 500km 떨어진 강에서 날아온 것으로 밝혀졌습니다.\n\n전문가는 강한 폭풍우가 물고기를 수만m 상공으로 빨아들여 잠시 얼렸다 땅에 떨어뜨린 것으로 추정하고 있는데요.\n\n이 지역에 물고기 비가 내린 것은 1974년 이후 이번이 4번째라고 하네요.\n\n누리꾼들은 \"몇 번 봐도 놀랄 듯 재앙의 전조란 말이 나올 만도\", \"악어 같은 게 떨어진다면 정말 무서울 듯\", \"저녁 찬거리 해결해준 거 아닌가\" 등의 반응을 보였습니다.\n\n(화면 출처 : 유튜브 Weird News·Interesting World·트위터 thaole12345678)\n\n\n☞더 자세한 정보\nhttps://news.sbs.co.kr/y/?id=N1007091872\n\n☞[오!클릭] 기사 모아보기 \nhttps://news.sbs.co.kr/y/t/?id=10000000168\n \n\n#SBS뉴스 #오클릭 #물고기\n\n▶SBS 뉴스 채널 구독하기 : https://n.sbs.co.kr/youtube \n▶SBS 뉴스 라이브 : https://n.sbs.co.kr/youtubeLive , https://n.sbs.co.kr/live \n\n▶SBS 뉴스 제보하기\n홈페이지: https://n.sbs.co.kr/inform \n애플리케이션: 'SBS뉴스' 앱 설치하고 제보 - https://n.sbs.co.kr/App \n카카오톡: 'SBS뉴스'와 친구 맺고 채팅 - https://pf.kakao.com/_ewsdq/chat \n페이스북: 'SBS뉴스' 메시지 전송 - https://www.facebook.com/sbs8news \n이메일: sbs8news@sbs.co.kr \n문자: #6000 \n전화: 02-2113-6000 \n\n홈페이지: https://news.sbs.co.kr/ \n페이스북: https://www.facebook.com/sbs8news \n트위터: https://www.twitter.com/sbs8news\n카카오톡: https://pf.kakao.com/_ewsdq\n인스타그램: https://www.instagram.com/sbsnews",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/gNCqySyeyus/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/gNCqySyeyus/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/gNCqySyeyus/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/gNCqySyeyus/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/gNCqySyeyus/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "SBS 뉴스",
        tags: [
          "SBS NEWS",
          "SBS 뉴스",
          "custom:뉴스넷",
          "format:리포트",
          "genre:국제",
          "location:서울",
          "sbs",
          "sbs 실시간",
          "series:오!클릭",
          "series:오뉴스",
          "source:영상",
          "type:방송",
          "기영",
          "뉴스 실시간",
          "뉸",
          "실시간뉴스",
          "에스비에스",
          "오클릭4",
          "찬완",
          "하늘에서 쏟아진 물고기",
        ],
        categoryId: "25",
        liveBroadcastContent: "none",
        localized: {
          title:
            '하늘에서 쏟아진 수백 마리…"재앙의 전조?" 쏟아진 목격 / SBS / 오클릭',
          description:
            "〈오! 클릭〉 마지막 검색어는 '하늘에서 쏟아진 물고기'입니다.\n\n도로에 은빛 비늘의 물고기들이 널브러져 있습니다.\n\n호주 북부의 작은 마을 '라자마누'에서 벌어진 일인데요, 물고기 수백 마리가 비와 함께 하늘에서 쏟아져 내린 것입니다.\n\n현장을 목격한 주민은 갑자기 하늘에서 물고기가 땅과 지붕으로 우수수 떨어졌고, 이 가운데 상당수는 죽지 않은 채 바닥에서 펄떡거렸다고 하는데요.\n\n이 물고기는 호주에서 흔히 볼 수 있는 농어과 민물고기로 약 500km 떨어진 강에서 날아온 것으로 밝혀졌습니다.\n\n전문가는 강한 폭풍우가 물고기를 수만m 상공으로 빨아들여 잠시 얼렸다 땅에 떨어뜨린 것으로 추정하고 있는데요.\n\n이 지역에 물고기 비가 내린 것은 1974년 이후 이번이 4번째라고 하네요.\n\n누리꾼들은 \"몇 번 봐도 놀랄 듯 재앙의 전조란 말이 나올 만도\", \"악어 같은 게 떨어진다면 정말 무서울 듯\", \"저녁 찬거리 해결해준 거 아닌가\" 등의 반응을 보였습니다.\n\n(화면 출처 : 유튜브 Weird News·Interesting World·트위터 thaole12345678)\n\n\n☞더 자세한 정보\nhttps://news.sbs.co.kr/y/?id=N1007091872\n\n☞[오!클릭] 기사 모아보기 \nhttps://news.sbs.co.kr/y/t/?id=10000000168\n \n\n#SBS뉴스 #오클릭 #물고기\n\n▶SBS 뉴스 채널 구독하기 : https://n.sbs.co.kr/youtube \n▶SBS 뉴스 라이브 : https://n.sbs.co.kr/youtubeLive , https://n.sbs.co.kr/live \n\n▶SBS 뉴스 제보하기\n홈페이지: https://n.sbs.co.kr/inform \n애플리케이션: 'SBS뉴스' 앱 설치하고 제보 - https://n.sbs.co.kr/App \n카카오톡: 'SBS뉴스'와 친구 맺고 채팅 - https://pf.kakao.com/_ewsdq/chat \n페이스북: 'SBS뉴스' 메시지 전송 - https://www.facebook.com/sbs8news \n이메일: sbs8news@sbs.co.kr \n문자: #6000 \n전화: 02-2113-6000 \n\n홈페이지: https://news.sbs.co.kr/ \n페이스북: https://www.facebook.com/sbs8news \n트위터: https://www.twitter.com/sbs8news\n카카오톡: https://pf.kakao.com/_ewsdq\n인스타그램: https://www.instagram.com/sbsnews",
        },
      },
    },
    {
      kind: "youtube#video",
      etag: "pH_i1gvqYka9aYJfucaLfgINcLY",
      id: "XvwnZUOZZDI",
      snippet: {
        publishedAt: "2023-02-23T08:29:46Z",
        channelId: "UCReO0narAXjFs59KFqqtE8g",
        title:
          "[1부] 유재석, 김숙과 도너츠 만들던 썰부터 송은이 회사 지분 인수 욕심까지?!😮",
        description:
          "진짜, 드디어, 결국 왔습니다...\n많은 분들이 기다리고 기다리던 유재석 탈골 방송 (거의) 풀버전 1부!\n정신없는 오프닝부터 유재석의 완물완궁, 탑3까지 영상으로 함께해요✌🏻\n(담당 PD는 편집하는 내내 귀에서 피를 흘렸다는 후문이...🥹)\n\n📌2부 영상은 다음 주 목요일에 올라옵니다! 많관부💛\n\n#송은이 #김숙 #유재석\n──────────────────\n💌 제작/협찬 및 비즈니스 문의: ad@vivolab.tv\n──────────────────\n비보티비 공식 인스타그램\n📍https://www.instagram.com/vivotv\n\n비보티비 트위터\n📍https://twitter.com/vivo119",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/XvwnZUOZZDI/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/XvwnZUOZZDI/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/XvwnZUOZZDI/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/XvwnZUOZZDI/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/XvwnZUOZZDI/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "VIVO TV - 비보티비",
        tags: [
          "송은이",
          "songeuni",
          "김숙",
          "kimsook",
          "金淑",
          "비밀보장",
          "팟캐스트",
          "비보",
          "컨텐츠랩비보",
          "TMI",
          "게스트",
          "유재석",
          "런닝맨",
          "놀면뭐하니",
          "무한도전",
          "유느님",
          "핑계고",
          "안테나",
          "남편은베짱이",
          "개그",
          "개그우먼",
          "개그맨",
          "코미디",
          "김수용",
          "추억",
          "400회",
          "하하",
          "박명수",
          "김용만",
          "이미주",
          "전소민",
          "조세호",
          "홍진경",
          "틴탑",
        ],
        categoryId: "23",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title:
            "[1부] 유재석, 김숙과 도너츠 만들던 썰부터 송은이 회사 지분 인수 욕심까지?!😮",
          description:
            "진짜, 드디어, 결국 왔습니다...\n많은 분들이 기다리고 기다리던 유재석 탈골 방송 (거의) 풀버전 1부!\n정신없는 오프닝부터 유재석의 완물완궁, 탑3까지 영상으로 함께해요✌🏻\n(담당 PD는 편집하는 내내 귀에서 피를 흘렸다는 후문이...🥹)\n\n📌2부 영상은 다음 주 목요일에 올라옵니다! 많관부💛\n\n#송은이 #김숙 #유재석\n──────────────────\n💌 제작/협찬 및 비즈니스 문의: ad@vivolab.tv\n──────────────────\n비보티비 공식 인스타그램\n📍https://www.instagram.com/vivotv\n\n비보티비 트위터\n📍https://twitter.com/vivo119",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "ed4l253Kxog8JidjAzVc98JKscc",
      id: "lqpJT1H84FU",
      snippet: {
        publishedAt: "2023-02-26T22:21:29Z",
        channelId: "UCxdayJ2v3MJk8eraNrYLzdQ",
        title:
          "메시 & 음바페, 더비전에서 터진 축구황제들의 콤비 플레이 #르클라시크더비 [리그1 25R HL/마르세유 vs PSG]",
        description:
          "#메시 #네이마르 #음바페 #리오넬메시 #르클라시크더비 #르클라시크 #더비 #마르세유 #올림피크 #드라마 #극장경기 #명승부 #프리킥 #버저비터 #파리생제르망 #파리생제르맹 #카타르 #월드컵 #메시 #25라운드 #네이마르 #음바페 #골든부트 #다닐루 #페레이라 #어시스트 #멀티골 #챔스 #챔피언스리그 #16강 #바이에른뮌헨 #에키티케 #헤나투산체스 #하키미 #파비앙루이스 #솔레르 #비티냐 #베라티 #축구 #해외축구 #라모스 #데뷔골 #자이르에머리",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/lqpJT1H84FU/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/lqpJT1H84FU/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/lqpJT1H84FU/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/lqpJT1H84FU/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/lqpJT1H84FU/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "파리 습제르맹 - Paris SBS-Germain",
        tags: [
          "PSG",
          "파리생제르망",
          "파리생제르맹",
          "파리",
          "프랑스",
          "리그앙",
          "리그1",
          "메시",
          "음바페",
          "네이마르",
          "라모스",
          "축구",
          "해외축구",
          "리오넬메시",
          "드라마",
          "극장경기",
          "명승부",
          "프리킥",
          "월드컵 #메시",
          "24라운드",
          "골든부트",
          "다닐루",
          "페레이라",
          "어시스트",
          "멀티골",
          "챔스",
          "챔피언스리그",
          "16강",
          "바이에른뮌헨",
          "에키티케",
          "헤나투산체스",
          "하키미",
          "파비앙루이스",
          "솔레르 #비티",
          "베라티",
          "데뷔",
          "역전골",
          "마르세유",
          "더비",
          "르클라시크",
          "르클라시크더비",
        ],
        categoryId: "17",
        liveBroadcastContent: "none",
        localized: {
          title:
            "메시 & 음바페, 더비전에서 터진 축구황제들의 콤비 플레이 #르클라시크더비 [리그1 25R HL/마르세유 vs PSG]",
          description:
            "#메시 #네이마르 #음바페 #리오넬메시 #르클라시크더비 #르클라시크 #더비 #마르세유 #올림피크 #드라마 #극장경기 #명승부 #프리킥 #버저비터 #파리생제르망 #파리생제르맹 #카타르 #월드컵 #메시 #25라운드 #네이마르 #음바페 #골든부트 #다닐루 #페레이라 #어시스트 #멀티골 #챔스 #챔피언스리그 #16강 #바이에른뮌헨 #에키티케 #헤나투산체스 #하키미 #파비앙루이스 #솔레르 #비티냐 #베라티 #축구 #해외축구 #라모스 #데뷔골 #자이르에머리",
        },
        defaultAudioLanguage: "en",
      },
    },
    {
      kind: "youtube#video",
      etag: "6_391Xd1LYelK8IpSKp14841V2I",
      id: "0r6bZjTU99w",
      snippet: {
        publishedAt: "2023-02-25T15:00:00Z",
        channelId: "UC3re3ueOE_6VZK85zlEUWFA",
        title:
          "[3-4회 하이라이트] 사기꾼한테 사기 쳐서 참교육하는 택시.. 아니 농부 이제훈의 통쾌한 사이다! #모범택시2 #SBSCatch",
        description:
          "[스브스캐치] 구독하기▶https://goo.gl/bnT3WD\n\n[3-4회 하이라이트] 사기꾼한테 사기 쳐서 참교육하는 택시.. \n아니 농부 이제훈의 통쾌한 사이다!\n#모범택시2 #SBSCatch\n\n스브스캐치 페이스북 ▶ https://goo.gl/MYWh4V\n스브스캐치 인스타그램 ▶ https://goo.gl/9kukCu\n모범택시2 홈페이지 ▶ https://programs.sbs.co.kr/drama/taxidriver2/about/73743",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/0r6bZjTU99w/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/0r6bZjTU99w/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/0r6bZjTU99w/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/0r6bZjTU99w/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/0r6bZjTU99w/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "SBS Catch",
        tags: [
          "드라마 추천",
          "모범택시2",
          "드라마 모범택시2",
          "SBS 모범택시2",
          "모범택시2 티저",
          "모범택시2 예고편",
          "모범택시2 명장면",
          "스브스캐치",
          "스브스캐치 드라마",
          "모범택시2 이제훈",
          "모범택시2 표예진",
          "림여사",
          "모범택시2 림여사",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title:
            "[3-4회 하이라이트] 사기꾼한테 사기 쳐서 참교육하는 택시.. 아니 농부 이제훈의 통쾌한 사이다! #모범택시2 #SBSCatch",
          description:
            "[스브스캐치] 구독하기▶https://goo.gl/bnT3WD\n\n[3-4회 하이라이트] 사기꾼한테 사기 쳐서 참교육하는 택시.. \n아니 농부 이제훈의 통쾌한 사이다!\n#모범택시2 #SBSCatch\n\n스브스캐치 페이스북 ▶ https://goo.gl/MYWh4V\n스브스캐치 인스타그램 ▶ https://goo.gl/9kukCu\n모범택시2 홈페이지 ▶ https://programs.sbs.co.kr/drama/taxidriver2/about/73743",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "NKnDRJ_J6349bOZETNR_3l3P2zw",
      id: "RlrDeAivv4w",
      snippet: {
        publishedAt: "2023-02-25T13:24:03Z",
        channelId: "UCOHM2N1YQdb-cHWxJxwBMLQ",
        title:
          "[아형✪하이라이트] 약 1500만 너튜버들이(=슈카x김계란x심으뜸x쯔양) 형님 학교 '디스' 하러 왔다👊 | 아는 형님 | JTBC 230225 방송",
        description:
          "[아형✪하이라이트] 약 1500만 너튜버들이(=슈카x김계란x심으뜸x쯔양) 형님 학교 '디스' 하러 왔다👊\n#아는형님 #토크하이라이트 #슈카김계란심으뜸쯔양\n\n📌 공홈에서 리플레이 : https://tv.jtbc.co.kr/jtbcbros\n📌 #티빙에서스트리밍 : https://tving.onelink.me/xHqC/1vihef6r\n\n〈아는 형님〉은 매주 토요일 저녁 8시 50분 본.방.사.수!",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/RlrDeAivv4w/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/RlrDeAivv4w/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/RlrDeAivv4w/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/RlrDeAivv4w/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/RlrDeAivv4w/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "아는형님 Knowingbros",
        tags: [
          "아는 형님",
          "형님",
          "형님 학교",
          "슈카",
          "김계란",
          "심으뜸",
          "쯔양",
          "강호동",
          "이수근",
          "서장훈",
          "김희철",
          "민경훈",
          "김영철",
          "이상민",
          "박영진",
          "이진호",
          "아는형님유튜버",
          "유튜버",
          "아형외개인동아리",
          "아형쯔양",
          "아형슈카",
          "아형김계란",
          "아형심으뜸",
          "피지컬100심으뜸",
          "힘으뜸",
          "피지컬갤러리",
          "슈카월드",
          "운동유튜버",
          "운동채널",
          "주식",
          "아형주식",
          "먹방",
          "쯔양먹방",
          "유튜브먹방",
          "아는형님하이라이트",
          "아는형님게임하이라이트",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title:
            "[아형✪하이라이트] 약 1500만 너튜버들이(=슈카x김계란x심으뜸x쯔양) 형님 학교 '디스' 하러 왔다👊 | 아는 형님 | JTBC 230225 방송",
          description:
            "[아형✪하이라이트] 약 1500만 너튜버들이(=슈카x김계란x심으뜸x쯔양) 형님 학교 '디스' 하러 왔다👊\n#아는형님 #토크하이라이트 #슈카김계란심으뜸쯔양\n\n📌 공홈에서 리플레이 : https://tv.jtbc.co.kr/jtbcbros\n📌 #티빙에서스트리밍 : https://tving.onelink.me/xHqC/1vihef6r\n\n〈아는 형님〉은 매주 토요일 저녁 8시 50분 본.방.사.수!",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "0M8oLNq8Yi9qO4-dUrETRnIn5SA",
      id: "128f-F3sGe0",
      snippet: {
        publishedAt: "2023-02-26T11:00:01Z",
        channelId: "UCZvCP6sWj75MwpUP4LVtpNw",
        title: "[몬 먹어도 고] MONSTA X 몬.먹.고 TEASER #2",
        description:
          "▶More information\nMONSTA X Official Fan cafe : http://cafe.daum.net/monsta-x\nMONSTA X Official Twitter : http://www.twitter.com/OfficialMonstaX\nMONSTA X Official Facebook : http://www.facebook.com/OfficialMonstaX\nMONSTA X Official Instagram : https://www.instagram.com/official_monsta_x\nMONSTA X Official Weibo : http://www.weibo.com/monstax\n\n#MONSTAX #몬스타엑스 #MONBEBE #몬먹고 #MONMUKGO",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/128f-F3sGe0/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/128f-F3sGe0/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/128f-F3sGe0/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/128f-F3sGe0/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/128f-F3sGe0/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "MONSTA X",
        tags: [
          "Kpop",
          "1theK",
          "Starshiptv",
          "starship",
          "loen",
          "로엔",
          "뮤비",
          "티져",
          "MV",
          "Teaser",
          "Dance practice",
          "신곡",
          "new",
          "song",
          "한류",
          "idol",
          "hallyu",
          "ロエン",
          "ミュージック",
          "ミュージックビデオ",
          "アイドル",
          "韓流",
          "韓国",
          "아이돌",
          "reality",
          "몬채널",
          "MONCHANNEL",
          "MON-CHANNEL",
          "making film",
          "behind",
          "MONSTA X",
          "MONSTA-X",
          "몬스타엑스",
          "몬엑",
          "MX",
          "DRAMARAMA",
          "THE CODE",
          "셔누",
          "형원",
          "기현",
          "민혁",
          "주헌",
          "아이엠",
          "SHOWNU",
          "HYUNGWON",
          "KIHYUN",
          "MINHYUK",
          "JOOHEON",
          "JOOHONEY",
          "IM",
          "REASON",
          "Beautiful Liar",
          "뷰티풀라이어",
          "뷰라",
          "몬 먹어도 고",
          "몬먹고",
          "몬고",
          "몬먹어도고",
          "자컨",
          "티저",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "[몬 먹어도 고] MONSTA X 몬.먹.고 TEASER #2",
          description:
            "▶More information\nMONSTA X Official Fan cafe : http://cafe.daum.net/monsta-x\nMONSTA X Official Twitter : http://www.twitter.com/OfficialMonstaX\nMONSTA X Official Facebook : http://www.facebook.com/OfficialMonstaX\nMONSTA X Official Instagram : https://www.instagram.com/official_monsta_x\nMONSTA X Official Weibo : http://www.weibo.com/monstax\n\n#MONSTAX #몬스타엑스 #MONBEBE #몬먹고 #MONMUKGO",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "tSoK8mNIGdW1Vx2PkU9cxrKstso",
      id: "QnOtDhIt0uw",
      snippet: {
        publishedAt: "2023-02-25T03:00:00Z",
        channelId: "UCiEEF51uRAeZeCo8CJFhGWw",
        title: "[선공개] 베테랑 킬러, 우수 직원 전도연 | 길복순 | 넷플릭스",
        description:
          "대기업 킬러 회사의 베테랑 직원인 길복순. 그녀를 우러러보는 인턴들 앞에서 실력을 선보인다.\r\n\r\n#길복순 #KillBoksoon #넷플릭스\r\n\r\n넷플릭스 채널 구독: https://bit.ly/2HUnqDr\r\n\r\nhttps://www.youtube.com/@NetflixKorea",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/QnOtDhIt0uw/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/QnOtDhIt0uw/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/QnOtDhIt0uw/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/QnOtDhIt0uw/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/QnOtDhIt0uw/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Netflix Korea 넷플릭스 코리아",
        tags: [
          "KillBoksoon",
          "Netflix",
          "길복순",
          "넷플릭스",
          "변성현",
          "설경구",
          "액션",
          "영화",
          "전도연",
          "킬러",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "[선공개] 베테랑 킬러, 우수 직원 전도연 | 길복순 | 넷플릭스",
          description:
            "대기업 킬러 회사의 베테랑 직원인 길복순. 그녀를 우러러보는 인턴들 앞에서 실력을 선보인다.\r\n\r\n#길복순 #KillBoksoon #넷플릭스\r\n\r\n넷플릭스 채널 구독: https://bit.ly/2HUnqDr\r\n\r\nhttps://www.youtube.com/@NetflixKorea",
        },
        defaultAudioLanguage: "en-US",
      },
    },
    {
      kind: "youtube#video",
      etag: "fmojaP5Hpr-Mo8zuYR0g1b9w4YQ",
      id: "tVaLKUQtgq4",
      snippet: {
        publishedAt: "2023-02-24T09:00:37Z",
        channelId: "UC1B6SalAoiJD7eHfMUA9QrA",
        title: "집 보러 왔습니다",
        description: "#스케치코미디 #숏박스 #부동산",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/tVaLKUQtgq4/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/tVaLKUQtgq4/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/tVaLKUQtgq4/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/tVaLKUQtgq4/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/tVaLKUQtgq4/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "숏박스",
        tags: ["숏박스", "스케치코미디", "개그"],
        categoryId: "23",
        liveBroadcastContent: "none",
        localized: {
          title: "집 보러 왔습니다",
          description: "#스케치코미디 #숏박스 #부동산",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "Fys8p0LrLcVeLvJ8YGBCT9RsfNg",
      id: "dOp0oWFHUWw",
      snippet: {
        publishedAt: "2023-02-23T00:00:01Z",
        channelId: "UCiEEF51uRAeZeCo8CJFhGWw",
        title: "더 글로리 파트2 | 공식 예고편 | 넷플릭스",
        description:
          "가혹한 희망, 더없는 폐허 그리고\n송혜교가 선사할 완벽한 지옥\n\n《더 글로리》 파트2 3월 10일, 오직 넷플릭스에서\n\n#넷플릭스 #더글로리_파트2 #TheGlory_Part2\n\n넷플릭스 채널 구독: https://bit.ly/2HUnqDr\n\nhttps://www.youtube.com/@NetflixKorea",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/dOp0oWFHUWw/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/dOp0oWFHUWw/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/dOp0oWFHUWw/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/dOp0oWFHUWw/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/dOp0oWFHUWw/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Netflix Korea 넷플릭스 코리아",
        tags: [
          "Netflix",
          "TheGlory",
          "TheGloryPart2",
          "강현남",
          "거룩한",
          "글로리",
          "김건우",
          "김은숙작가",
          "김히어라",
          "넷플릭스",
          "넷플릭스시리즈",
          "더글로리",
          "더글로리파트2",
          "드라마",
          "문동은",
          "박성훈",
          "박연진",
          "복수",
          "비극",
          "손명오",
          "송혜교",
          "안길호감독",
          "염혜란",
          "영광",
          "용서",
          "이도현",
          "이사라",
          "임지연",
          "전재준",
          "정성일",
          "주여정",
          "차주영",
          "최혜정",
          "하도영",
          "학교폭력",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "더 글로리 파트2 | 공식 예고편 | 넷플릭스",
          description:
            "가혹한 희망, 더없는 폐허 그리고\n송혜교가 선사할 완벽한 지옥\n\n《더 글로리》 파트2 3월 10일, 오직 넷플릭스에서\n\n#넷플릭스 #더글로리_파트2 #TheGlory_Part2\n\n넷플릭스 채널 구독: https://bit.ly/2HUnqDr\n\nhttps://www.youtube.com/@NetflixKorea",
        },
        defaultAudioLanguage: "en-US",
      },
    },
    {
      kind: "youtube#video",
      etag: "t8NMcyEHUUREmJtTYDA4Mi1iGpQ",
      id: "1Ml4lpHA0NM",
      snippet: {
        publishedAt: "2023-02-25T00:00:00Z",
        channelId: "UCVXx89z5j3gkQMGScNqmWjw",
        title:
          "뱃살 너무 빠져서 고민 3탄! 무조건 6kg 빠지는 양배추 다이어트요리 ! 꼭 해보세요!/다이어트요리 양배추요리💚",
        description:
          "뱃살 너무 빠져서 고민 3탄! 무조건 6kg 빠지는 양배추 다이어트요리 ! 꼭 해보세요!/다이어트요리 양배추요리💚\n[재료]\n양배추 350g\n당근 200g\n오이 200g\n소금 1+1/2큰술\n부침용팩두부 1모\n참기름 1작은술\n고운소금 1/4작은술\n후추 약간\n1작은술 = 5ml\n1큰술 = 15m\n함께해요 맛나요리 네이버 밴드 가입\nhttps://band.us/@mannarecipe\n\n맛나 스케치 delicious sketch\nhttps://www.youtube.com/channel/UCr8m6FvqeL8y80-Hx-vjw9w",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/1Ml4lpHA0NM/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/1Ml4lpHA0NM/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/1Ml4lpHA0NM/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/1Ml4lpHA0NM/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/1Ml4lpHA0NM/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "함께해요 맛나요리",
        tags: [
          "양배추",
          "양배추 말이",
          "양배추말이",
          "쌈",
          "쌈 말이",
          "배추쌈",
          "배추 쌈",
          "양배추 쌈",
          "맛나요리",
          "함께해요",
          "함께해요 맛나요리",
          "한식",
          "레시피",
          "korean",
          "korea",
          "korean food",
          "korea food",
          "koreafood",
        ],
        categoryId: "26",
        liveBroadcastContent: "none",
        localized: {
          title:
            "뱃살 너무 빠져서 고민 3탄! 무조건 6kg 빠지는 양배추 다이어트요리 ! 꼭 해보세요!/다이어트요리 양배추요리💚",
          description:
            "뱃살 너무 빠져서 고민 3탄! 무조건 6kg 빠지는 양배추 다이어트요리 ! 꼭 해보세요!/다이어트요리 양배추요리💚\n[재료]\n양배추 350g\n당근 200g\n오이 200g\n소금 1+1/2큰술\n부침용팩두부 1모\n참기름 1작은술\n고운소금 1/4작은술\n후추 약간\n1작은술 = 5ml\n1큰술 = 15m\n함께해요 맛나요리 네이버 밴드 가입\nhttps://band.us/@mannarecipe\n\n맛나 스케치 delicious sketch\nhttps://www.youtube.com/channel/UCr8m6FvqeL8y80-Hx-vjw9w",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "U9V9gHyZqx7f1LfW6KjfjtNkfjs",
      id: "8i_wZQoqbwU",
      snippet: {
        publishedAt: "2023-02-26T15:00:04Z",
        channelId: "UCqwUnggBBct-AY2lAdI88jQ",
        title: "BABYMONSTER - Introducing AHYEON",
        description:
          "#BABYMONSTER #베이비몬스터 #AHYEON #아현 #YG_NEW_GROUP #YG\n\nMore about BABYMONSTER @\nOfficial YouTube https://www.youtube.com/@officialBABYMONSTER\nOfficial Instagram https://www.instagram.com/babymonster_ygofficial\nOfficial Facebook https://www.facebook.com/BABYMONSTER.ygofficial\nOfficial Twitter https://twitter.com/YGBABYMONSTER_\nOfficial TikTok https://tiktok.com/@babymonster_yg_tiktok\nOfficial Weibo https://weibo.com/u/7811488144\nOfficial bilibili https://space.bilibili.com/3493127232948989",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/8i_wZQoqbwU/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/8i_wZQoqbwU/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/8i_wZQoqbwU/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/8i_wZQoqbwU/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/8i_wZQoqbwU/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "BABYMONSTER",
        tags: [
          "BABYMONSTER",
          "베이비몬스터",
          "베몬",
          "BABYMON",
          "BAEMON",
          "하람",
          "아현",
          "루카",
          "치키타",
          "파리타",
          "로라",
          "아사",
          "HARAM",
          "AHYEON",
          "RUKA",
          "CHIQUITA",
          "PHARITA",
          "RORA",
          "ASA",
        ],
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title: "BABYMONSTER - Introducing AHYEON",
          description:
            "#BABYMONSTER #베이비몬스터 #AHYEON #아현 #YG_NEW_GROUP #YG\n\nMore about BABYMONSTER @\nOfficial YouTube https://www.youtube.com/@officialBABYMONSTER\nOfficial Instagram https://www.instagram.com/babymonster_ygofficial\nOfficial Facebook https://www.facebook.com/BABYMONSTER.ygofficial\nOfficial Twitter https://twitter.com/YGBABYMONSTER_\nOfficial TikTok https://tiktok.com/@babymonster_yg_tiktok\nOfficial Weibo https://weibo.com/u/7811488144\nOfficial bilibili https://space.bilibili.com/3493127232948989",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "BLXpDZR3L4HIle9YmQuCzLDiKw4",
      id: "gR3QjJPM1xs",
      snippet: {
        publishedAt: "2023-02-23T23:13:23Z",
        channelId: "UC7uDyFIqExDnfXAIZqumFrQ",
        title:
          "짱구집 도면을 한국 건축가와 일본 부동산 전문가가 분석해보았다.(f. 마츠다 부장님)",
        description:
          "#일본주택 #짱구집 #오사카 #일본여행 #일본\n\n\u200b오사카에사는사람들tv X 셜록현준 @osaka544 \n\n짱구집 도면을 한국 건축가와 일본 부동산 전문가가 분석해보았다.\n(f. 마츠다 부장님)",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/gR3QjJPM1xs/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/gR3QjJPM1xs/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/gR3QjJPM1xs/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/gR3QjJPM1xs/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/gR3QjJPM1xs/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "셜록현준",
        tags: [
          "짱구집",
          "일본 건축",
          "일본 주택",
          "일본 집",
          "오사카에 사는 사람들",
          "마츠다부장",
          "마츠다",
          "오사사",
          "마부장",
          "일본 여행",
          "일본 주택 특징",
          "일본 집 소개",
          "짱구 집",
        ],
        categoryId: "27",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title:
            "짱구집 도면을 한국 건축가와 일본 부동산 전문가가 분석해보았다.(f. 마츠다 부장님)",
          description:
            "#일본주택 #짱구집 #오사카 #일본여행 #일본\n\n\u200b오사카에사는사람들tv X 셜록현준 @osaka544 \n\n짱구집 도면을 한국 건축가와 일본 부동산 전문가가 분석해보았다.\n(f. 마츠다 부장님)",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "aMKMwbkPiv8cYBgu6b0tlodmSsg",
      id: "PJwBsOmQcCs",
      snippet: {
        publishedAt: "2023-02-26T04:16:54Z",
        channelId: "UCfCOEG2kjX_x4KAdWX-YUcA",
        title:
          "위험한(?) 멕시코 한국과 물가 비교부터 시장까지 - 멕시코, 세계여행 [81]",
        description:
          "감사합니다! \n\n\n카메라 - 고프로 11, 인스타360 1인치 \nMusic - Epidemic sound\n인스타그램- \nhttps://instagram.com/no.mad.shaun?igshid=YmMyMTA2M2Y= \nEmail-tobeistodo5@gmail.com",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/PJwBsOmQcCs/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/PJwBsOmQcCs/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/PJwBsOmQcCs/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/PJwBsOmQcCs/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/PJwBsOmQcCs/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "노마드션 No mad Shaun",
        tags: ["여행유튜버", "세계여행", "멕시코"],
        categoryId: "19",
        liveBroadcastContent: "none",
        localized: {
          title:
            "위험한(?) 멕시코 한국과 물가 비교부터 시장까지 - 멕시코, 세계여행 [81]",
          description:
            "감사합니다! \n\n\n카메라 - 고프로 11, 인스타360 1인치 \nMusic - Epidemic sound\n인스타그램- \nhttps://instagram.com/no.mad.shaun?igshid=YmMyMTA2M2Y= \nEmail-tobeistodo5@gmail.com",
        },
      },
    },
    {
      kind: "youtube#video",
      etag: "YBn0gza-SzaCHbIva3NdEbK3sB0",
      id: "528XMujOZGw",
      snippet: {
        publishedAt: "2023-02-25T13:30:18Z",
        channelId: "UC78PMQprrZTbU0IlMDsYZPw",
        title:
          "오픈 전부터 우당탕탕💫 티격태격💥 서진이네 모음 #highlight  #유료광고포함 #서진이네 EP.1",
        description:
          "티빙에서 스트리밍 : https://tving.onelink.me/xHqC/30a78d6f\n\n일곱 빛깔 호수를 품은 멕시코에서\n#서진이네 OPEN!\n\n식당 경영에 진심인 사장 #이서진\n이사로 승진한 #정유미\n주방의 실세로 거듭난 #박서준\n서진이네 분위기 메이커 #최우식 \n설거지요정 새 인턴 #김태형\n\n오늘도 어서오세요 :)\n서진이네 EP.1\ntvN 매주 금요일 오후 8시 50분!\n\n#티빙에서스트리밍",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/528XMujOZGw/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/528XMujOZGw/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/528XMujOZGw/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/528XMujOZGw/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/528XMujOZGw/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "tvN",
        tags: [
          "김말이",
          "김밥",
          "김태형",
          "나영석",
          "대박기원",
          "떡볶이",
          "라면",
          "만두",
          "먹방",
          "박서준",
          "분식",
          "뷔",
          "사장",
          "서진이네",
          "승진",
          "식당",
          "실세",
          "요리",
          "음식",
          "이사",
          "이서진",
          "인턴",
          "장사",
          "정유미",
          "정직원",
          "직금",
          "최우식",
          "튀김",
          "티빙에서스트리밍",
          "판매",
          "핫도그",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title:
            "오픈 전부터 우당탕탕💫 티격태격💥 서진이네 모음 #highlight  #유료광고포함 #서진이네 EP.1",
          description:
            "티빙에서 스트리밍 : https://tving.onelink.me/xHqC/30a78d6f\n\n일곱 빛깔 호수를 품은 멕시코에서\n#서진이네 OPEN!\n\n식당 경영에 진심인 사장 #이서진\n이사로 승진한 #정유미\n주방의 실세로 거듭난 #박서준\n서진이네 분위기 메이커 #최우식 \n설거지요정 새 인턴 #김태형\n\n오늘도 어서오세요 :)\n서진이네 EP.1\ntvN 매주 금요일 오후 8시 50분!\n\n#티빙에서스트리밍",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "EORGOcfktbpbiqz790qP3z6ydLo",
      id: "QpsnqkhQH_s",
      snippet: {
        publishedAt: "2023-02-26T08:20:49Z",
        channelId: "UCZVD--cl8FLRn7kmSudAuBA",
        title: "잘하는 집을 안 가봐서 그래",
        description:
          "잘하는 집을 안 가봐서 그래\n\n멜론: http://kko.to/gqbc6QOviD\n벅스: https://music.bugs.co.kr/track/6191173\n지니: https://www.genie.co.kr/X5MIF2\n바이브: https://vibe.naver.com/track/62096144\n플로: https://www.music-flo.com/detail/track/ezzzyhlzy\n\n작사,작곡- 과나\nVocal- 과나\nSynth- 과나\nGuitar- 성남시핸드릭스\nMixing & Mastering- 과나\n기획,연출 - 과나\n그림,애니메이션 - 과나 \n그림 도움- 과나아빠 \n로토스코핑- 과나, 과나아빠 \n편집 - 과순 \n남사원,부장 목소리- 과나 \n여사원 목소리 - 과순\n춤 - 과나, 과순  \n\n인스타그램: @gwana9102",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/QpsnqkhQH_s/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/QpsnqkhQH_s/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/QpsnqkhQH_s/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/QpsnqkhQH_s/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/QpsnqkhQH_s/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "과나gwana",
        tags: ["홍어", "굴", "세대갈등"],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "잘하는 집을 안 가봐서 그래",
          description:
            "잘하는 집을 안 가봐서 그래\n\n멜론: http://kko.to/gqbc6QOviD\n벅스: https://music.bugs.co.kr/track/6191173\n지니: https://www.genie.co.kr/X5MIF2\n바이브: https://vibe.naver.com/track/62096144\n플로: https://www.music-flo.com/detail/track/ezzzyhlzy\n\n작사,작곡- 과나\nVocal- 과나\nSynth- 과나\nGuitar- 성남시핸드릭스\nMixing & Mastering- 과나\n기획,연출 - 과나\n그림,애니메이션 - 과나 \n그림 도움- 과나아빠 \n로토스코핑- 과나, 과나아빠 \n편집 - 과순 \n남사원,부장 목소리- 과나 \n여사원 목소리 - 과순\n춤 - 과나, 과순  \n\n인스타그램: @gwana9102",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "6qC5iwS8BIqUbX163etRV8kzXf4",
      id: "scwZ3DD1B88",
      snippet: {
        publishedAt: "2023-02-26T10:15:02Z",
        channelId: "UC12YJZLancDKojjbRunyhZA",
        title: "맛과 행운! 두마리 토끼를 다 잡은 초대박 해루질!!!",
        description:
          "#해루질 #catchandcook #모니모\n\n진석기시대 x 삼성생명 모니모 경품 이벤트\n\n참여 방법\n\n1. 아래의 URL 주소를 통해 모니모 앱을 다운받고 신규 가입한다.\n- https://www.samsunglife.com/s/DG9\n\n2. 아래의 구글 양식에 접속해 경품 이벤트 신청서를 작성한다.\n- https://forms.gle/DzYimKzW449E7Ak88\n\n* 모니모 신규 가입자 정보와 구글 양식 신청서 정보가 동일해야 합니다!\n* 1인 1회 참여 가능 (중복 신청 불가)\n* 낚시 용품 / 비 낚시 용품 선택 가능 (선택한 카테고리 내에서 추첨)\n* 미성년자 참여 불가\n- 접수 기간 : 2023년 2월 26일 ~ 2023년 3월 4일 (토) PM 6:00\n- 당첨자 발표 : 2023년 3월 5일 (일) PM 7:00 \n(진석기시대 채널 실시간 라이브 추첨)\n\n----------------------------------------------------------\n해루질 문의 : 마검포 레져하우스 (태안)\n010-9160-1261\n----------------------------------------------------------\n\n비지니스 메일 : jinseokgi333@gmail.com\n인스타그램 : https://www.instagram.com/jinseokgi/\nJSG SHOP : https://m.smartstore.naver.com/jsg_shop\n\n----------------------------------------------------------",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/scwZ3DD1B88/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/scwZ3DD1B88/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/scwZ3DD1B88/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/scwZ3DD1B88/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/scwZ3DD1B88/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "진석기시대",
        categoryId: "24",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title: "맛과 행운! 두마리 토끼를 다 잡은 초대박 해루질!!!",
          description:
            "#해루질 #catchandcook #모니모\n\n진석기시대 x 삼성생명 모니모 경품 이벤트\n\n참여 방법\n\n1. 아래의 URL 주소를 통해 모니모 앱을 다운받고 신규 가입한다.\n- https://www.samsunglife.com/s/DG9\n\n2. 아래의 구글 양식에 접속해 경품 이벤트 신청서를 작성한다.\n- https://forms.gle/DzYimKzW449E7Ak88\n\n* 모니모 신규 가입자 정보와 구글 양식 신청서 정보가 동일해야 합니다!\n* 1인 1회 참여 가능 (중복 신청 불가)\n* 낚시 용품 / 비 낚시 용품 선택 가능 (선택한 카테고리 내에서 추첨)\n* 미성년자 참여 불가\n- 접수 기간 : 2023년 2월 26일 ~ 2023년 3월 4일 (토) PM 6:00\n- 당첨자 발표 : 2023년 3월 5일 (일) PM 7:00 \n(진석기시대 채널 실시간 라이브 추첨)\n\n----------------------------------------------------------\n해루질 문의 : 마검포 레져하우스 (태안)\n010-9160-1261\n----------------------------------------------------------\n\n비지니스 메일 : jinseokgi333@gmail.com\n인스타그램 : https://www.instagram.com/jinseokgi/\nJSG SHOP : https://m.smartstore.naver.com/jsg_shop\n\n----------------------------------------------------------",
        },
        defaultAudioLanguage: "ko",
      },
    },
    {
      kind: "youtube#video",
      etag: "9QlnDb3tZufw_ahG_PQedS1YTCM",
      id: "RVLGijsCpKw",
      snippet: {
        publishedAt: "2023-02-24T09:04:10Z",
        channelId: "UCGPBgBHGdmr1VSaK_3Oitqw",
        title: "사랑하기 싫어 (Tired of falling in love)",
        description:
          "Provided to YouTube by Collab Asia Music\n\n사랑하기 싫어 (Tired of falling in love) · 지아 (Zia)\n\n사랑하기 싫어 (Tired of falling in love)\n\n℗ 니즈뮤직\n\nAuto-generated by YouTube.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/RVLGijsCpKw/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/RVLGijsCpKw/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/RVLGijsCpKw/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/RVLGijsCpKw/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/RVLGijsCpKw/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Various Artists - Topic",
        tags: ["지아 (Zia)", "사랑하기 싫어 (Tired of falling in love)"],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "사랑하기 싫어 (Tired of falling in love)",
          description:
            "Provided to YouTube by Collab Asia Music\n\n사랑하기 싫어 (Tired of falling in love) · 지아 (Zia)\n\n사랑하기 싫어 (Tired of falling in love)\n\n℗ 니즈뮤직\n\nAuto-generated by YouTube.",
        },
      },
    },
  ],
  nextPageToken: "CBkQAA",
  pageInfo: {
    totalResults: 200,
    resultsPerPage: 25,
  },
};
